pipeline {
    agent any
    environment {
        CONTAINER_REGISTRY = "azurecontainer77"
        REGISTRY_URL = "azurecontainer77.azurecr.io"
        AZURESP = credentials('azuresp')
        RESOURCE_GROUP = "acr"
        dockerImage = ''
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: ' https://github.com/SaiPrabhu88/neom-aks.git']])
            }
        }
        stage('Build Image') {
            steps {
                withCredentials([azureServicePrincipal(credentialsId: 'azuresp', subscriptionIdVariable: 'SUBS_ID', clientIdVariable: 'CLIENT_ID', clientSecretVariable: 'CLIENT_SECRET', tenantIdVariable: 'TENANT_ID')]) {
                sh '''
                az login --service-principal -var subscription_id="$SUBS_ID" -var tenant_id="$TENANT_ID" -var client_id="$CLIENT_ID" -var client_secret="$CLIENT_SECRET"
                '''
                }
            }
        }
    }
}