pipeline {
    agent any
    environment {

        AZURESVP = credentials('azuresp')
        CONTAINER_REGISTRY = "azurecontainer77.azurecr.io"
        REGISTRY_URL = "azurecontainer77.azurecr.io"
        AZURESP = credentials('azuresp')
        RESOURCE_GROUP = "acr"
        IMAGE_NAME = "sampleapp"
        IMAGE_TAG = "latest"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: ' https://github.com/SaiPrabhu88/neom-aks.git']])
            }
        }
        stage('Connect to ACR') {
            steps {
                sh 'az login --service-principal -u $AZURESVP_CLIENT_ID -p $AZURESVP_CLIENT_SECRET -t $AZURESVP_TENANT_ID'
                sh 'az account set -s $AZURESVP_SUBSCRIPTION_ID'
                sh 'az acr login --name $CONTAINER_REGISTRY'
            }
        }
        stage('Build and Push Image') {
            steps {
                sh 'docker build -t $CONTAINER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG sampleapp/.'
                sh 'docker push $CONTAINER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG'
            }
        }
    }
}